version: '3'

services:
  db:
    image: mysql:8.0.19
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apl
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"

  ubuntu:
    container_name: ubuntu
    build: ./ubuntu
    volumes:
      - ./ubuntu/src:/var/www/laravel
    working_dir: /var/www/laravel
    ports:
      - "10080:80"

